import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useAppDispatch } from "npm/redux/hooks";
import {
  addAccessToken,
  addUserData,
  type userDataPayload,
} from "npm/redux/userSlice";
import { type zodCustomError } from "npm/types";
import { api } from "npm/utils/api";
import { type ChangeEvent, type FormEvent, useState } from "react";
import { z } from "zod";
import jwt from "jsonwebtoken";

export default function Login() {
  const [user, setUser] = useState({
    email: "",
    password: "",
  });
  const dispatch = useAppDispatch();
  const router = useRouter();
  const [errors, setErrors] = useState<zodCustomError[]>([]);
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setErrors([]);
    const { name, value } = e.target;
    setUser((prevUser) => ({
      ...prevUser,
      [name]: value,
    }));
  };
  const loginUser = api.auth.signIn.useMutation({
    onSuccess: async (response) => {
      if (response.success && response.data?.accessToken) {
        dispatch(addAccessToken({ accessToken: response.data.accessToken }));
        const payload = jwt.decode(
          response.data.accessToken,
        ) as userDataPayload;
        dispatch(addUserData(payload));
        await router.push("/interests");
      }
    },
  });
  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    try {
      // user validation schema
      const userSchema = z.object({
        email: z.string({ required_error: "email is required" }).email(),
        password: z.string({ required_error: "password is required" }),
      });
      // validating inputs with the user schema
      const userValidationResponse = userSchema.safeParse(user);
      // showing the error messages
      if (!userValidationResponse.success) {
        const errArr: zodCustomError[] = [];
        const { errors: err } = userValidationResponse.error;
        for (const error of err) {
          errArr.push({ for: error.path[0], message: error.message });
        }
        setErrors(errArr);
        throw err;
      }
      setErrors([]);
      loginUser.mutate(user);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-[90vh] flex-col items-center justify-center ">
        <div className="flex min-w-[576px] flex-col items-center justify-center rounded-xl border-2 border-[#C1C1C1] p-10">
          <h1 className="mb-10 text-3xl font-semibold text-black">Login</h1>
          <form
            onSubmit={handleSubmit}
            className="flex w-full flex-col gap-y-10"
          >
            <div>
              <p className="mb-1 text-lg font-normal">Email</p>
              <input
                type="text"
                name="email"
                placeholder="Enter"
                value={user.email}
                onChange={handleChange}
                className="w-full rounded-md border border-[#C1C1C1] p-3"
              />
              <p className="absolute mt-1 text-xs font-normal text-red-500">
                {errors.find((error) => error.for === "email")?.message}
              </p>
            </div>
            <div>
              <p className="mb-1 text-lg font-normal">Password</p>
              <input
                type="password"
                name="password"
                placeholder="Enter"
                value={user.password}
                onChange={handleChange}
                className="w-full rounded-md border border-[#C1C1C1] p-3"
              />
              <p className="absolute mt-1 text-xs font-normal text-red-500">
                {errors.find((error) => error.for === "password")?.message}
              </p>
            </div>
            <button type="submit" className="w-full bg-black p-3 text-white">
              {loginUser.isPending ? "submitting..." : "Login"}
            </button>
          </form>
          <div className="mt-14">
            <p className="text-base font-normal">
              Don’t have an Account?{" "}
              <span>
                <Link href={"/"} className="font-medium">
                  Sign up
                </Link>
              </span>
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
